Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "advisor-learn-dev-setup"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.27.25"
  config.vm.synced_folder "..", "/mnt/components"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    rm /etc/resolv.conf
    echo "nameserver 8.8.8.8" > /etc/resolv.conf

    sudo apt-get update

    sudo apt-get -y install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    sudo apt-key fingerprint 0EBFCD88

    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

    sudo apt-get update

    sudo apt-get -y install nodejs jq docker-ce docker-compose gnupg2 pass sshpass


    docker volume create portainer_data
    docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer


    # sh /vagrant/scripts/docker_add_registry.sh
    # sh /vagrant/scripts/docker_deploy.sh


  SHELL
end
